# Generated by Django 3.0.3 on 2020-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='debt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalCost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
